version = 1

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  plugins = [
    "react",
    "angular",
    "angularjs"
  ]
  environment = ["nodejs"]

[[transformers]]
name = "standardjs"

[[transformers]]
name = "prettier"